# Generated by Django 5.0.2 on 2024-06-26 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("festival_title", models.TextField()),
                ("festival_content", models.TextField()),
                ("festival_category", models.IntegerField()),
                ("festival_price", models.FloatField(null=True)),
                ("festival_address", models.TextField(null=True)),
                ("festival_address_detail", models.TextField(null=True)),
                ("festival_location", models.TextField(null=True)),
                ("festival_start", models.DateField(null=True)),
                ("festival_end", models.DateField(null=True)),
                ("host_info", models.TextField(null=True)),
                ("host_phone", models.TextField(null=True)),
                ("provider_info", models.TextField(null=True)),
                ("provider_url", models.TextField(null=True)),
                ("thumbnail_path", models.ImageField(upload_to="festival/%Y/%m/%d")),
                ("status", models.BooleanField(default=1)),
            ],
            options={
                "db_table": "tbl_festival",
            },
        ),
    ]
