# Generated by Django 5.0.2 on 2024-06-26 14:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("member_email", models.TextField()),
                ("member_nickname", models.TextField()),
                ("member_phone", models.TextField(null=True)),
                ("member_address", models.TextField(null=True)),
                (
                    "member_gender",
                    models.SmallIntegerField(
                        choices=[(0, "선택안함"), (1, "남성"), (2, "여성")],
                        default=0,
                        null=True,
                    ),
                ),
                ("member_birth", models.IntegerField(null=True)),
                ("member_marketing_agree", models.BooleanField(default=0, null=True)),
                ("member_privacy_agree", models.BooleanField(default=0, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(-1, "정지"), (0, "탈퇴"), (1, "활동중")], default=1
                    ),
                ),
                ("member_type", models.CharField(max_length=10)),
                ("member_keyword1", models.TextField(null=True)),
                ("member_keyword2", models.TextField(null=True)),
                ("member_keyword3", models.TextField(null=True)),
                ("member_recommended_activity_model", models.TextField(null=True)),
                ("member_recommended_teenplay_model", models.TextField(null=True)),
                ("member_recommended_club_model", models.TextField(null=True)),
            ],
            options={
                "db_table": "tbl_member",
            },
        ),
    ]
