# Generated by Django 5.0.2 on 2024-06-26 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("club", "0003_clubcategory_clubpostreply"),
        ("festival", "0001_initial"),
        ("member", "0002_adminaccount_memberdeletereason_and_more"),
        ("pay", "0001_initial"),
        ("teenplay_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("activity_title", models.TextField()),
                ("activity_content", models.TextField()),
                ("recruit_start", models.DateTimeField()),
                ("recruit_end", models.DateTimeField()),
                ("activity_intro", models.TextField(null=True)),
                ("activity_address_location", models.TextField(null=True)),
                ("activity_address_detail", models.TextField(null=True)),
                ("thumbnail_path", models.ImageField(upload_to="activity/%Y/%m/%d")),
                ("banner_path", models.ImageField(upload_to="activity/%Y/%m/%d")),
                ("activity_start", models.DateTimeField()),
                ("activity_end", models.DateTimeField()),
                ("status", models.BooleanField(default=1)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teenplay_server.category",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.club"
                    ),
                ),
                (
                    "festival",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="festival.festival",
                    ),
                ),
                (
                    "pay",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pay.pay"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_activity",
            },
        ),
        migrations.CreateModel(
            name="ActivityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("image_path", models.ImageField(upload_to="activity/%Y/%m/%d")),
                ("status", models.BooleanField(default=1)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.activity",
                    ),
                ),
            ],
            options={
                "db_table": "tbl_activity_image",
            },
        ),
        migrations.CreateModel(
            name="ActivityLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.BooleanField(default=1)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.activity",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_activity_like",
            },
        ),
        migrations.CreateModel(
            name="ActivityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(-1, "참가대기"), (0, "취소"), (1, "참가중")], default=0
                    ),
                ),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.activity",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_activity_member",
            },
        ),
        migrations.CreateModel(
            name="ActivityReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reply_content", models.TextField()),
                ("status", models.BooleanField(default=1)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="activity.activity",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_activity_reply",
            },
        ),
    ]
