# Generated by Django 5.0.2 on 2024-06-26 14:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("member", "0002_adminaccount_memberdeletereason_and_more"),
        ("teenplay_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("club_name", models.TextField()),
                ("club_intro", models.TextField()),
                ("club_info", models.TextField(null=True)),
                ("club_profile_path", models.ImageField(upload_to="club/%Y/%m/%d")),
                ("club_banner_path", models.ImageField(upload_to="club/%Y/%m/%d")),
                ("status", models.BooleanField(default=1)),
                (
                    "club_main_category",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teenplay_server.category",
                    ),
                ),
                (
                    "club_region",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teenplay_server.region",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club",
            },
        ),
    ]
