# Generated by Django 5.0.2 on 2024-06-26 14:51

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0001_initial"),
        ("member", "0002_adminaccount_memberdeletereason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("alarm_status", models.BooleanField(default=1)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(-1, "가입대기"), (0, "탈퇴"), (1, "가입중")], default=-1
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.club"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club_member",
            },
            managers=[
                ("enabled_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="ClubNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("notice_title", models.TextField()),
                ("notice_content", models.TextField()),
                ("status", models.BooleanField(default=1)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.club"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club_notice",
            },
        ),
        migrations.CreateModel(
            name="ClubPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("post_title", models.TextField()),
                ("post_content", models.TextField()),
                ("image_path", models.ImageField(upload_to="club_post/%Y/%m/%d")),
                ("view_count", models.IntegerField(default=0)),
                ("status", models.BooleanField(default=1)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.club"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club_post",
            },
            managers=[
                ("enabled_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
