# Generated by Django 5.0.2 on 2024-06-26 14:51

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_clubmember_clubnotice_clubpost"),
        ("member", "0002_adminaccount_memberdeletereason_and_more"),
        ("teenplay_server", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("status", models.BooleanField(default=1)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="teenplay_server.category",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.club"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club_category",
            },
        ),
        migrations.CreateModel(
            name="ClubPostReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reply_content", models.TextField()),
                ("status", models.BooleanField(default=1)),
                (
                    "club_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="club.clubpost"
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="member.member"
                    ),
                ),
            ],
            options={
                "db_table": "tbl_club_post_reply",
            },
            managers=[
                ("enabled_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
